apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: dockercoins
build:
  artifacts:
  - image: dockercoins/hasher
    context: ./hasher
  - image: dockercoins/rng
    context: ./rng
  - image: dockercoins/webui
    context: ./webui
  - image: dockercoins/worker
    context: ./worker
deploy:
  kustomize:
    paths:
    - ./kubernetes/base
profiles:
- name: local
  activation:
  - kubeContext: minikube
  deploy:
    kustomize:
      paths:
      - ./kubernetes/overlays/local
