apiVersion: skaffold/v1beta13
kind: Config
metadata:
  name: dockercoins
build:
  artifacts:
  - image: dockercoins/hasher
    context: ./hasher
  - image: dockercoins/rng
    context: ./rng
  - image: dockercoins/webui
    context: ./webui
  - image: dockercoins/worker
    context: ./worker
deploy:
  kustomize:
    path: "./kubernetes/base"
profiles:
- name: local
  activation:
  - kubeContext: minikube
  deploy:
    kustomize:
      path: "./kubernetes/overlays/local"
